#cloud-config
packages:
- socat
write_files:
- path: /etc/rancher/k3s/config.yaml
  owner: root:root
  permissions: '0644'
  content: |
    tls-san:
    - "k3s.multipass"
    docker: true
    write-kubeconfig-mode: "0644"
- path: /etc/docker/daemon.json
  owner: root:root
  permissions: '0644'
  content: |
    {
      "builder": {
        "gc": {
          "defaultKeepStorage": "20GB",
          "enabled": true
        }
      },
      "experimental": false,
      "features": {
        "buildkit": true
      },
      "hosts": [
        "tcp://0.0.0.0:2375",
        "unix:///var/run/docker.sock"
      ],
      "tls": false
    }
- path: /etc/systemd/system/docker.service.d/override.conf
  owner: root:root
  permissions: '0644'
  content: |
    [Service]
    ExecStart=
    ExecStart=/usr/bin/dockerd --containerd=/run/containerd/containerd.sock
runcmd:
- echo 127.0.1.1 k3s k3s.multipass >> /etc/hosts
- echo k3s > /etc/hostname
- hostname k3s
- mkdir -p /etc/apt/keyrings
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
- echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
- apt-get update
- apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
- usermod -aG docker ubuntu
- curl -sfL https://get.k3s.io | sh -
- echo "export DOCKER_BUILDKIT=1" >> /home/ubuntu/.bashrc

# TODO - zsh add profile
# Remote docker?
